name: Deploy to Stage

on:
  push:
    branches:
      - stage

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull and Run Container
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/fabriplay-ui:stage
          docker stop fabriplayui-stage || true
          docker rm fabriplayui-stage || true
          docker run -d \
            --name fabriplayui-stage \
            --restart always \
            -p 3000:3000 \
            ${{ secrets.DOCKER_USERNAME }}/fabriplay-ui:stage

     
           
